### ISSUE TITLE
PSQLException: FATAL: role "dev" does not exist

### ISSUE THREAD

**Issue by PraveenTalari** [ShockN745/My-Java-Archetype#1] opened 2019-03-26 11:41 UTC
Getting the following exception

org.postgresql.util.PSQLException: FATAL: role "dev" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455) ~[postgresql-9.4.1212.jre7.jar:9.4.1212.jre7]

Do I need to create some roles,tables etc?

Didn't find those steps anywhere in
https://github.com/FlorianKempenich/My-Java-Archetype/blob/master/README.md
or
https://www.professionalbeginner.com/post/11

BTW, I have added the following dependency in build.gradle
// https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
compile group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'

**Comment by HelloThisIsFlo** [comment] 2019-03-26 12:00
Hi,
I'm glad to see my blog is helping people :) 

The role `dev` seems to be missing . . . but ideally, you shouldn't **have** to create it. I built this prototype as an out-of-the-box working example of the architecture I describe.

I built this showcase quite a while ago, I'll need a couple of days to find the time to fix it, but I definitely will. In the meantime, you can either try to create a role named `dev` as a superuser if you're using a docker-based postgres (meaning you can't "break" things"). And if that's a bit too complex, which is totally understandable, just stay posted and I'll let you know once I fixed/updated the project ;)

Thanks for the feedback :)

**Comment by HelloThisIsFlo** [comment] 2019-03-26 12:04
Yep, it seems you need to create:
* A role `dev` with password `dev`
* A database `javaarchetype`

You can see the values in the configuration: https://github.com/FlorianKempenich/My-Java-Archetype/blob/master/src/main/resources/application.yml

But again, you're 100% right, you shouldn't _have_ to do this. I'll update with a docker-based one click init script later this week ;)

**Comment by HelloThisIsFlo** [comment] 2019-03-27 12:18
Here you go: 24e9affc638dfb1dbd5d29738040ca84d6d70eb3 🙃

I updated the project with 3 scripts to get started in one click:
*  `./run_tests.sh`
* `./start_app_with_inmemory.sh`
* `./start_app_with_inmemory.sh`

Only need _Docker_ installed, and everything should work out of the box 😃
Let me know if you still have problems running the project 😉 I'm closing the issue for now.

**Comment by HelloThisIsFlo** [comment] 2019-03-27 12:19
Oh also, I didn't have to add `jaxb-api` for the project to compile. 
Are you using the included gradle wrapper? -> `./gradlew`

Maybe try with the new scripts and let me know if it's still needed ;)

**Closed as completed by HelloThisIsFlo** 2019-03-27 12:19 UTC

**Comment by PraveenTalari** [comment] 2019-04-19 13:41
you have mentioned ./start_app_with_inmemory.sh twice instead of ./start_app_with_database.sh in README.md

and
.sh files won't work in windows , right ?

BTW what all the URLs should be accessed after starting the app ?

Can only access
http://0.0.0.0:8080/books

**Comment by HelloThisIsFlo** [comment] 2019-04-29 10:49
Hey,

Sorry for the late response, been busy lately :) 

To answer your question: **Yes, `.sh` files are made for Unix-like systems**. I think the equivalent on Windows would be a `.bat` file but I had 0 experience with that.  
**Solution:** What you can do is read the content of what each `.sh` file does and reproduces it manually. There aren't many steps, and for the `docker` parts, simply copy pasting the `docker` command will work on windows :) 

Regarding the endpoints, this was meant as an architectural showcase, not an actually useful app. There are a couple of endpoints but not many. You can find the list by exploring the `Controllers` in [`src/main/java/com/professionalbeginner/presentation/controller`](https://github.com/FlorianKempenich/My-Java-Archetype/tree/master/src/main/java/com/professionalbeginner/presentation/controller). You will find that there are 5 endpoints:
* **Book** - `/books` - Retrieve all books
* **Book** - `/books/detail` - Retrieve a book details
* **Book** - `/books/new` - Create new book
* **Book** - `/books/newReview` - Add a new review to an existing book
* **Account** - `/users/new` - Add a new User

Hope that helps :)
